# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corders.proto\"\x9a\x01\n\x0cOrderRequest\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x10\n\x08order_id\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x0b\n\x03qty\x18\x05 \x01(\x02\x12\x17\n\x06status\x18\x06 \x01(\x0e\x32\x07.Status\x12\x13\n\x04side\x18\x07 \x01(\x0e\x32\x05.Side\x12\x0c\n\x04time\x18\x08 \x01(\x03\"\x1f\n\x0bReadRequest\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\"-\n\x0cReadResponse\x12\x1d\n\x06orders\x18\x01 \x03(\x0b\x32\r.OrderRequest\"C\n\rDeleteRequest\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x10\n\x08order_id\x18\x03 \x01(\t\"\x1e\n\rCountResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\")\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t*9\n\x06Status\x12\x07\n\x03NEW\x10\x00\x12\n\n\x06\x46ILLED\x10\x01\x12\x0c\n\x08\x43\x41NCELED\x10\x02\x12\x0c\n\x08REJECTED\x10\x03*\x19\n\x04Side\x12\x08\n\x04SELL\x10\x00\x12\x07\n\x03\x42UY\x10\x01\x32\xe2\x01\n\x06Orders\x12\x1f\n\x04Load\x12\x0c.ReadRequest\x1a\t.Response\x12\"\n\x06\x43reate\x12\r.OrderRequest\x1a\t.Response\x12#\n\x04Read\x12\x0c.ReadRequest\x1a\r.ReadResponse\x12\"\n\x06Update\x12\r.OrderRequest\x1a\t.Response\x12#\n\x06\x44\x65lete\x12\x0e.DeleteRequest\x1a\t.Response\x12%\n\x05\x43ount\x12\x0c.ReadRequest\x1a\x0e.CountResponseb\x06proto3')

_STATUS = DESCRIPTOR.enum_types_by_name['Status']
Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
_SIDE = DESCRIPTOR.enum_types_by_name['Side']
Side = enum_type_wrapper.EnumTypeWrapper(_SIDE)
NEW = 0
FILLED = 1
CANCELED = 2
REJECTED = 3
SELL = 0
BUY = 1


_ORDERREQUEST = DESCRIPTOR.message_types_by_name['OrderRequest']
_READREQUEST = DESCRIPTOR.message_types_by_name['ReadRequest']
_READRESPONSE = DESCRIPTOR.message_types_by_name['ReadResponse']
_DELETEREQUEST = DESCRIPTOR.message_types_by_name['DeleteRequest']
_COUNTRESPONSE = DESCRIPTOR.message_types_by_name['CountResponse']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
OrderRequest = _reflection.GeneratedProtocolMessageType('OrderRequest', (_message.Message,), {
  'DESCRIPTOR' : _ORDERREQUEST,
  '__module__' : 'orders_pb2'
  # @@protoc_insertion_point(class_scope:OrderRequest)
  })
_sym_db.RegisterMessage(OrderRequest)

ReadRequest = _reflection.GeneratedProtocolMessageType('ReadRequest', (_message.Message,), {
  'DESCRIPTOR' : _READREQUEST,
  '__module__' : 'orders_pb2'
  # @@protoc_insertion_point(class_scope:ReadRequest)
  })
_sym_db.RegisterMessage(ReadRequest)

ReadResponse = _reflection.GeneratedProtocolMessageType('ReadResponse', (_message.Message,), {
  'DESCRIPTOR' : _READRESPONSE,
  '__module__' : 'orders_pb2'
  # @@protoc_insertion_point(class_scope:ReadResponse)
  })
_sym_db.RegisterMessage(ReadResponse)

DeleteRequest = _reflection.GeneratedProtocolMessageType('DeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEREQUEST,
  '__module__' : 'orders_pb2'
  # @@protoc_insertion_point(class_scope:DeleteRequest)
  })
_sym_db.RegisterMessage(DeleteRequest)

CountResponse = _reflection.GeneratedProtocolMessageType('CountResponse', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRESPONSE,
  '__module__' : 'orders_pb2'
  # @@protoc_insertion_point(class_scope:CountResponse)
  })
_sym_db.RegisterMessage(CountResponse)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'orders_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

_ORDERS = DESCRIPTOR.services_by_name['Orders']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=397
  _STATUS._serialized_end=454
  _SIDE._serialized_start=456
  _SIDE._serialized_end=481
  _ORDERREQUEST._serialized_start=17
  _ORDERREQUEST._serialized_end=171
  _READREQUEST._serialized_start=173
  _READREQUEST._serialized_end=204
  _READRESPONSE._serialized_start=206
  _READRESPONSE._serialized_end=251
  _DELETEREQUEST._serialized_start=253
  _DELETEREQUEST._serialized_end=320
  _COUNTRESPONSE._serialized_start=322
  _COUNTRESPONSE._serialized_end=352
  _RESPONSE._serialized_start=354
  _RESPONSE._serialized_end=395
  _ORDERS._serialized_start=484
  _ORDERS._serialized_end=710
# @@protoc_insertion_point(module_scope)
