# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: symbols.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsymbols.proto\"\x86\x01\n\rSymbolRequest\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x12\n\nbase_asset\x18\x03 \x01(\t\x12\x13\n\x0bquote_asset\x18\x04 \x01(\t\x12\x13\n\x0bqty_rounder\x18\x05 \x01(\x05\x12\x15\n\rprice_rounder\x18\x06 \x01(\x05\"\x1f\n\x0bReadRequest\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\".\n\x0cReadResponse\x12\x1e\n\x06orders\x18\x01 \x03(\x0b\x32\x0e.SymbolRequest\"1\n\rDeleteRequest\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\"\x1e\n\rCountResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\")\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\xc4\x01\n\x07Symbols\x12#\n\x06\x43reate\x12\x0e.SymbolRequest\x1a\t.Response\x12#\n\x04Read\x12\x0c.ReadRequest\x1a\r.ReadResponse\x12#\n\x06Update\x12\x0e.SymbolRequest\x1a\t.Response\x12#\n\x06\x44\x65lete\x12\x0e.DeleteRequest\x1a\t.Response\x12%\n\x05\x43ount\x12\x0c.ReadRequest\x1a\x0e.CountResponseb\x06proto3')



_SYMBOLREQUEST = DESCRIPTOR.message_types_by_name['SymbolRequest']
_READREQUEST = DESCRIPTOR.message_types_by_name['ReadRequest']
_READRESPONSE = DESCRIPTOR.message_types_by_name['ReadResponse']
_DELETEREQUEST = DESCRIPTOR.message_types_by_name['DeleteRequest']
_COUNTRESPONSE = DESCRIPTOR.message_types_by_name['CountResponse']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
SymbolRequest = _reflection.GeneratedProtocolMessageType('SymbolRequest', (_message.Message,), {
  'DESCRIPTOR' : _SYMBOLREQUEST,
  '__module__' : 'symbols_pb2'
  # @@protoc_insertion_point(class_scope:SymbolRequest)
  })
_sym_db.RegisterMessage(SymbolRequest)

ReadRequest = _reflection.GeneratedProtocolMessageType('ReadRequest', (_message.Message,), {
  'DESCRIPTOR' : _READREQUEST,
  '__module__' : 'symbols_pb2'
  # @@protoc_insertion_point(class_scope:ReadRequest)
  })
_sym_db.RegisterMessage(ReadRequest)

ReadResponse = _reflection.GeneratedProtocolMessageType('ReadResponse', (_message.Message,), {
  'DESCRIPTOR' : _READRESPONSE,
  '__module__' : 'symbols_pb2'
  # @@protoc_insertion_point(class_scope:ReadResponse)
  })
_sym_db.RegisterMessage(ReadResponse)

DeleteRequest = _reflection.GeneratedProtocolMessageType('DeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEREQUEST,
  '__module__' : 'symbols_pb2'
  # @@protoc_insertion_point(class_scope:DeleteRequest)
  })
_sym_db.RegisterMessage(DeleteRequest)

CountResponse = _reflection.GeneratedProtocolMessageType('CountResponse', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRESPONSE,
  '__module__' : 'symbols_pb2'
  # @@protoc_insertion_point(class_scope:CountResponse)
  })
_sym_db.RegisterMessage(CountResponse)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'symbols_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

_SYMBOLS = DESCRIPTOR.services_by_name['Symbols']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SYMBOLREQUEST._serialized_start=18
  _SYMBOLREQUEST._serialized_end=152
  _READREQUEST._serialized_start=154
  _READREQUEST._serialized_end=185
  _READRESPONSE._serialized_start=187
  _READRESPONSE._serialized_end=233
  _DELETEREQUEST._serialized_start=235
  _DELETEREQUEST._serialized_end=284
  _COUNTRESPONSE._serialized_start=286
  _COUNTRESPONSE._serialized_end=316
  _RESPONSE._serialized_start=318
  _RESPONSE._serialized_end=359
  _SYMBOLS._serialized_start=362
  _SYMBOLS._serialized_end=558
# @@protoc_insertion_point(module_scope)
