version: '3.7'
services:
  mongo:
    image: mongo:4.4.14
    restart: always
    command: mongod --quiet --logpath /dev/null
    networks:
      - bot_net
    volumes:
      - ./mongo_db_data:/data/db
      - ./mongo_db_dump:/dump
    ports:
      - 27027:27017
  db_api:
    build:
      context: ./db_api
      dockerfile: Dockerfile
    volumes:
      - ./db_api:/app
    env_file: ./db_api/.env
    networks:
      - bot_net
    restart: on-failure
    ports:
      - 8020:50051
    depends_on:
      - mongo
  rabbitmq:
    image: rabbitmq:latest
    volumes:
      - ./rabbit_data:/var/lib/rabbitmq
    ports:
      - 15672:15672
    networks:
      - bot_net
networks:
  bot_net:
    external: false
    driver: bridge